name: Benchmark

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      reuse:
        description: "reuse: Reuse existing benchmark server if possible"
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  # run benchmark
  benchmark:
    uses: Cysharp/Actions/.github/workflows/benchmark-execute.yaml@main
    with:
      environment: benchmark
      comment-behavior: ${{ matrix.comment-behavior }}
      benchmark-name: "magiconion-${{ github.event.issue.number || (inputs.reuse && 'wf' || github.run_number) }}"
      benchmark-config: "perf/BenchmarkApp/configs/benchmark_${{ github.event_name }}.yaml"
    secrets: inherit

  cleanup-failed:
    if: ${{ always() }}
    needs: [benchmark]
    uses: Cysharp/Actions/.github/workflows/benchmark-cleanup.yaml@main
    with:
      environment: benchmark
    secrets: inherit
